version: '3.7'

services:

  redis:
    container_name: matrix-redis
    image: redis:6.0.6-buster
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - ./deploy/redis_data:/data

  app:
    container_name: matrix-app
    image: matrix/app
    ports: ["5003:5000"]
    restart: unless-stopped
    user: "${UID}:${GID}"
    working_dir: /app
    build: ./deploy
    depends_on: [redis]
    env_file:
      - ./.env
    volumes:
      - ./:/app
    command: uwsgi --yaml /app/deploy/uwsgi.yml:app

  queue:
    container_name: matrix-queue
    image: matrix/app
    restart: unless-stopped
    user: "${UID}:${GID}"
    working_dir: /app
    build: ./deploy
    depends_on: [redis]
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - ./logs/supervisor:/var/log/supervisor
      - ./deploy/supervisord.conf:/etc/supervisor/conf.d/workers.conf
    command: /usr/bin/supervisord
