version: '3.7'

services:

  app:
    container_name: matrix-app
    image: matrix/app
    ports: ["5003:5000"]
    restart: unless-stopped
    user: "${UID}:${GID}"
    working_dir: /app
    build: ./deploy
    env_file:
      - ./.env
    volumes:
      - ./:/app
    command: uwsgi --yaml /app/deploy/uwsgi.yml:app
