app:
  module: wsgi:application
  master: 1
  vacuum: 1
  auto-procname: 1
  buffer-size: 8192
  post-buffering: 8192
  pidfile: /tmp/uwsgi.pid
  max-requests: 10000
  max-worker-lifetime: 21600
  lazy: 1
  lazy-apps: 1
  touch-reload: /app/touch_reload
  wsgi-disable-file-wrapper: 1
  catch-exceptions: 1
  reload-on-exception: 1
  disable-logging: 1

  http: 0.0.0.0:5000
  processes: 2
  harakiri: 600
  py-autoreload: 1
